site_name: '🧪 The MLOps Cookbook'
repo_url: https://github.com/Matesanz/mlops-course
repo_name: Matesanz/mlops-course
site_url: https://matesanz.github.io/mlops-course/
theme:
  name: material
  theme:
  palette:
    primary: teal
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
  custom_dir: "docs/overrides"

plugins:
  - search
  - autorefs
  - awesome-pages
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
  - mkdocs-jupyter:
      include_source: True


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
    - Getting Started:
      - index.md
      - setup.md
    - MLFlow Basics:
      - basics/index.md
      - basics/1-connect_to_mlflow.ipynb
      - basics/2-creating_an_experiment.ipynb
      - basics/3-creating_a_run.ipynb
      - basics/4-logging_metrics.ipynb
      - basics/5-logging_artifacts.ipynb
      - basics/6-logging_models.ipynb
      - basics/7-model_registry.ipynb
      - basics/8-model_staging.ipynb
    - MLFLow Advanced:
      - advanced/model_serving.md
    - Tutorials:
      - tutorials/index.md
      - tutorials/1-full_model_training.ipynb
      - tutorials/2-full_model_evaluation.ipynb

watch:
  - docs
