# launch mlflow server
version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - PYTHON_VERSION=3.11
        - POETRY=1.6.1
    tty: true

    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000


    volumes:
      # Mounts the project folder to '/workspace'.
      - ..:/workspace:cached

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    ports:
      - 5000:5000
    volumes:
      - ../mlruns:/mlruns
      - ../mlartifacts:/mlartifacts
    
    command: mlflow server --host 0.0.0.0 --backend-store-uri ./mlruns --artifacts-destination /mlartifacts --dev
